### PR TITLE
V8.6

### PR DESCRIPTION
**Pull request by Zimmi48**
I propose this as an alternative to #45. This is just a merge of the `V8.6` branch as it was before #43 and #44.

### CODE REVIEW

**Comment by spitters** [comment]
Thanks.
Travis is unhappy:
```
File "./implementations/ZType_integers.v", line 4, characters 2-23:

Error:

Cannot find a physical path bound to logical path matching suffix

Bignums.SpecViaZ.
```

**Comment by Zimmi48** [comment]
Indeed, the problem comes from #41 which switched to using the external Bignums library without updating `.travis.yml`. I will push a tentative fix.

**Comment by Zimmi48** [comment]
OK it looks like Travis is happy now.

**Comment by spitters** [comment]
@Zimmi48 Thanks!

**Comment by Zimmi48** [comment]
Thanks @spitters! Next step would be doing the same thing for Corn. Are you the maintainer over there as well?

**Pull request merged**
