### PR TITLE
Add OPAM file

### PR DESCRIPTION
**Pull request by maximedenes**
This should be tested by someone who uses OPAM.

### CODE REVIEW

**Comment by spitters** [comment]
Are you sure we want the opam file here? I'd expect that we need a replacement for this one:
https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-math-classes/coq-math-classes.1.0.7/opam

**Comment by maximedenes** [comment]
That one is for math-classes 1.0.7. The design of OPAM makes it so that you have to duplicate this file for each version, AFAIK. Here I provide one that will build the master branch of the repo.

**Comment by spitters** [comment]
Still, shouldn't it go to 
https://github.com/coq/opam-coq-archive/blob/master/released/packages/...
How will the installation of corn pick this up?

**Comment by maximedenes** [comment]
That repo is for released versions.

**Comment by maximedenes** [comment]
Ok, this seems to work (we tested it with Enrico).

**Comment by maximedenes** [comment]
> How will the installation of corn pick this up?

I will update the .travis.yml file there.

**Comment by maximedenes** [comment]
@spitters see https://github.com/c-corn/corn/pull/56

Could you merge this one so that we can test the other one?

**Pull request merged**
